### PR TITLE
v0.7.0

### LINKED ISSUE #14: Safer token storage
See if we can lock that `token.json` file down or something, or store it as an env variable and then check it out every time?

Very least some kind of `chmod` so an malicious attack would have to sudo at least (?)

### LINKED ISSUE #16: Better support for older noders
Right now everything is very ES6-entric but it would be better to do a `src/` and `bin/` or something where the distribution or `bin/` file was run through like the babel or something. Those promises be risky.

And then also add to the docs about minimum node versions and stuff.

### LINKED ISSUE #24: Error trying to remove labels from a repo with no labels
There is an error when trying to remove labels from a repo with no labels, should instead just say "no labels to remove" and redirect to the main menu

### PR DESCRIPTION
**Pull request by himynameisdave**
- [x] ~~Closes #16 - Better support for older noders~~ `git-label` requires node `>= 4.0.0`
- [x] Closes #14 - Safer token storage
- [x] Closes #24 - Error when trying to remove labels in a repo with no labels

### CODE REVIEW

**Comment by Jameskmonger** [comment]
Added safer token storage in pull request #29

**Comment by himynameisdave** [comment]
@Jameskmonger just doing some final code review and then this stuff will be merged in

**Comment by Jameskmonger** [comment]
Nice one @himynameisdave!

**Comment by himynameisdave** [comment]
@Jameskmonger how do you reset the password if need be?

**Comment by Jameskmonger** [comment]
Resetting the token will allow you to reset the password. Buttercup doesn't currently support changing the password on an archive.

**Pull request merged**
