### PR TITLE
v0.7.3-alpha

### LINKED ISSUE #35: Display friendlier error
I think we should be showing a friendlier error than the "Encrypted content has been tampered with" when the user enters the incorrect password.

### LINKED ISSUE #38: Allow resetting the token if you can't access it
Allowing the user to reset their token if they can't access the archive (a forgotten password kind of feature) would mean that they can delete the archive if it exists, and creates a new one.

It would prevent any issues similar to last night! :stuck_out_tongue:

### LINKED ISSUE #42: Password displayed in plain text
When entering your password to unlock the archived token (after you've already successfully set it), the password is displayed in plain text.

### LINKED ISSUE #43: Will not accept custom package file
```
npm v3.6.0
node v5.6.0
```

Running `git-labelmaker`, enter my password, and choose `Add Labels From Package`.  I'm prompted for a path.  I have tried all of these (test file located at each)

```
packages/github_labels.json
github_labels.json
.github_labels.json
```

contents of file

```
[
  { "name": "ready", "color": "#159818" },
  { "name": "blocked", "color": "#e11d21" },
  { "name": "open comments", "color": "#eb6420" },
  { "name": "proposal-discussion", "color": "#84b6eb" },
  { "name": "question", "color": "#cc317c" },
  { "name": "On Hold", "color": "#666666" },
  { "name": "Revision Needed", "color": "#bfdadc" }
]
```

I hope this helps solve an issue - or improve the docs!   Thanks for your help.

### LINKED ISSUE #45: Mention that this doesn't work with GH Enterprise atm
We should document it in the readme that the api call is made to the public GitHub API and will not work on a private/GH enterprise repo. [`git-label`](https://github.com/jasonbellamy/git-label) supports this feature however I chose to [hardcore the api in](https://github.com/himynameisdave/git-labelmaker/blob/master/bin/utils/configGitLabel.js#L11) because it was less overhead... eventually I would like `git-labelmaker` to just know/ask what api to use.

### LINKED ISSUE #47: Deprecate versions 0.7.0 and 0.7.1-alpha
```
$ npm deprecate git-labelmaker@0.7.0 "critical bug fixed in v0.7.2"
$ npm deprecate git-labelmaker@0.7.1-alpha "critical bug fixed in v0.7.2"
```

This will give deprecation warnings to anyone installing those versions.

### PR DESCRIPTION
**Pull request by himynameisdave**
@Jameskmonger open any pull requests for `v0.7.3` against this branch/PR :smile: 
- [ ] - ~~Closes #35 Display Friendlier error~~ will be dealt with after we get a working `0.7.3-alpha` released
- [x] - Closes #38 Allow resetting the token if you can't access it
- [ ] - Closes #42 Password displayed in plain text
- [x] - Closes #43 Will not accept custom package file
- [x] - Closes #45 Mention the hardcoded GH API in the readme
- [x] - Closes #47 Deprecate versions 0.7.0 and 0.7.1-alpha

### CODE REVIEW

**Comment by Jameskmonger** [comment]
Nice - will do @himynameisdave!

**Comment by himynameisdave** [comment]
I am going to merge in everything here, do a release called `0.7.3-alpha`, and then we can fix #35 separately and release a proper `0.7.3` (or `0.7.4`?)

**Comment by himynameisdave** [comment]
In the future, I would like releases to be smaller so that we can have a faster release cycle. Some of these bugs have persisted for users for several days which is shitty and pretty uncool.

**Comment by Jameskmonger** [comment]
Yeah that sounds good to me. I'll jump on the friendlier error issue when I can.

**Pull request merged**
