### PR TITLE
Fixed #15: Add remove all option

### LINKED ISSUE #15: "Clear All" option
"Clear All" option would be rad. It would delete all current labels in a repo.

### PR DESCRIPTION
**Pull request by Jameskmonger**
This ties in with the 'confirm' dialog of the standard removal option

### CODE REVIEW

**Comment by Jameskmonger** [comment]
This fixes #15

**Comment by himynameisdave** [comment]
@Jameskmonger just going to wait until #14 is merged and then `v0.7.0` will be complete, then I will merge this pull in :smile:

**Comment by Jameskmonger** [comment]
No problem @himynameisdave - I'll get on that this evening!

**Comment by himynameisdave** [comment]
@Jameskmonger thanks man, appreciate it!

**Comment by Jameskmonger** [comment]
All done @himynameisdave !

**Comment by Jameskmonger** [comment]
Want me to sort the conflicts out on this @himynameisdave ?

**Comment by himynameisdave** [comment]
Merged changes into #58

**Pull request closed without merging**
