### PR TITLE
v0.8.0

### LINKED ISSUE #15: "Clear All" option
"Clear All" option would be rad. It would delete all current labels in a repo.

### LINKED ISSUE #21: Allow RGB colours
Rather than only accepting 3/6 digit hex colours, RGB colours could also be accepted as an input.

### LINKED ISSUE #46: Allow saving all labels from a repository as a package
I think we should allow users to dump all the labels from a repository, so that they can then apply that setup to other repositories.

This is blocked by #43

### LINKED ISSUE #59: Buttercup throwing error
Not sure wtf is going on, but here's a log of the error:

screen shot 2016-03-21 at 7 46 02 pm

Happened when trying to run it for the first time in like a month

### PR DESCRIPTION
**Pull request by himynameisdave**
`v0.8.0` release
- [x] Closes #15
- [x] Closes #21 
- [x] Closes #46 
- [x] Resolves #59

### CODE REVIEW

**Comment by NewAlexandria** [comment]
🎬 looking forward to trying it.  post-upgrade an error is thrown, so I need to investigate if I broke anything

```
module.js:440
    throw err;
    ^

Error: Cannot find module '__buttercup/classes/Archive.js'
```

**Comment by himynameisdave** [comment]
@NewAlexandria that error is sometime seen if you have a local copy of `git-labelmaker` that you're developing and you run `npm link`... it can sometimes get confused about where to look for the credentials. Try to uninstall globally and then re-install and this error should be resolved.

**Comment by NewAlexandria** [comment]
Can you upload an example `.json` of the custom labels?  I'd like to be sure that I'm using the right format.  Getting

```
/usr/local/lib/node_modules/git-labelmaker/node_modules/git-label/dist/lib/request.js:28
      resolve(res.body);
                 ^

TypeError: Cannot read property 'body' of undefined
```

I can file a ticket if you want.  I'm really excited about this tool for teams, and want to help make it robust.

**Comment by NewAlexandria** [comment]
Oh, I just needed to upgrade to `npm 3.9.0`.  `node v6`

**Comment by himynameisdave** [comment]
@NewAlexandria noted, thanks!

**Pull request merged**
